# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:

  matrix:
    - PYTHON: "C:\\Python27-conda32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-conda64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"

install:
  - ps: ./bin/install_python.ps1

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # For debugging python-version and architecture.
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - ps: $condadeps = get-content requirements/miniconda.txt | select-string -NotMatch -Pattern '#'
  - ps: echo CONDADEPS $condadeps
  - ps: conda install --yes --quiet $condadeps
  - "pip install -r requirements\\execution.txt"
  - "python setup.py install"

build: false

test_script:
    - ps: |
        if ($env:PYTHON_VERSION -eq "3.4") {
            &bin/run_tests.ps1 all
        } else {
            &bin/run_tests.ps1 code
        }
