# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:

  matrix:
    - PYTHON: "C:\\Python27-conda32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-conda64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"

install:
  # Install miniconda Python
  - "powershell ./bin/install_python.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Keep in-sync: requirements/miniconda.txt
  - "conda install --yes --quiet pip setuptools nose sphinx numpy scipy pandas>=0.15 matplotlib"
  - "python setup.py install"

build: false

test_script:
  - >
    nosetests --with-doctest --doctest-extension=.rst 
    --doctest-options=+NORMALIZE_WHITESPACE,+ELLIPSIS,+REPORT_UDIFF 
    --with-coverage 
    --cover-package=pandalone.components,pandalone.mappings,pandalone.pndlcmd,pandalone.utils,pandalone.xlsutils  
    --cover-min-percentage=60";
