## TravisCI config
#
sudo: false
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  # - "3.8-dev"  # too slow!
matrix:
  allow_failures:
    - python: 3.5
    #- python: "3.8-dev"

before_install:


install:
    - python --version
    - pip install -e .[test]
    - pip list

script:
    - |
        if [[ "$TRAVIS_PYTHON_VERSION" = '3.5' ]]; then
            echo "+++ Checking all TCs, DTs & Coverage....";
            python setup.py test_all
        else
            echo "+++ Checking only TCs....";
            python setup.py test_code
        fi

    -   echo "+++ Checking install...."
        python setup.py install
        python setup.py build

    - |
        echo "+++  Checking archives for PyPI repo..."
        python setup.py sdist bdist_wheel

    - |
        echo "+++ Checking site...."
        pip install -e .[test,doc]
        python setup.py build_sphinx

    - |
        echo "+++ Checking README for PyPy...."
        pip install -e .[dev]
        ./bin/check_readme.sh

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then pip install coveralls && coveralls; fi

