## TravisCI config
#
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
    ## From: http://conda.pydata.org/docs/travis.htm
    ## Another one: https://gist.github.com/dan-blanchard/7045057
    #- sudo apt-get update
    - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a	## Useful for debugging any conda issues
  
    - deps="`grep -v \# requirements/miniconda.txt`"
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $deps
    - source activate test-environment

    - pip install nose -IU   ## Conda's nose is rotten, and `python setup.py nosetests` fails!

install:
  - pip install -r requirements/execution.txt
  - pip install coveralls

# command to run tests
script:
    - |
        if [[ $TRAVIS_PYTHON_VERSION = '2.7' ]]; then 
            echo #python setup.py build_sphinx ## TODO: Imitate readthedocs env.
        fi

    - |
        if [[ "$TRAVIS_PYTHON_VERSION" = '3.4' ]]; then 
            nose_args="--with-doctest --doctest-extension=.rst --doctest-options=+NORMALIZE_WHITESPACE,+ELLIPSIS,+REPORT_UDIFF";
            nose_args="$nose_args --with-coverage --cover-package=pandalone.components,pandalone.mappings,pandalone.pndlcmd,pandalone.utils  --cover-min-percentage=80";
            echo "RUNNING: nosetests $nose_args"
        fi; nosetests $nose_args

    - python setup.py sdist bdist_wheel             ## Create archives for PyPI repo.

    ## Ensure README valid ReST for PyPI.
    ##  In case it fails, improve the filtering-code in ``setup.py``.
    - python setup.py --long-description | rst2html.py  --halt=warning > /dev/null

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then coveralls; fi

