## TravisCI config
#
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
    ## From: http://conda.pydata.org/docs/travis.htm
    ## Another one: https://gist.github.com/dan-blanchard/7045057
    #- sudo apt-get update
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a	## Useful for debugging any conda issues

    - deps="`grep -v \# requirements/miniconda.txt`"
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $deps
    - source activate test-environment

install:
    - pip install -r requirements/development.txt -r requirements/execution.txt
    - python setup.py develop
    - python setup.py build
    # - python setup.py install ## NO, requirements installed in "develop' mode.

script:
    - |
        echo "+++ Checking README for PyPy...."
        ./bin/check_readme.sh

    - |
        echo "+++ Checking site...."
        python setup.py build_sphinx

    - |
        echo "+++  Checking archives for PyPI repo..."
        python setup.py sdist bdist_wheel

    - |
        if [[ "$TRAVIS_PYTHON_VERSION" = '3.4' ]]; then
            echo "+++ Checking all TCs, DTs & Coverage....";
            python setup.py test_all
        else
            echo "+++ Checking only TCs....";
            python setup.py test_code
        fi

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then coveralls; fi

