## TravisCI config
#
sudo: false
language: python
python:
  - 3.6
  - 3.7
  - 3.8

before_install:


install:
    - python --version
    - pip install -e .[test]
    - pip list

script:
    - pytest

    -   echo "+++ Checking install...."
        python setup.py install
        python setup.py build

    - |
        echo "+++  Checking archives for PyPI repo..."
        python setup.py sdist bdist_wheel

    - |
        echo "+++ Checking site...."
        pip install -e .[test,doc]
        python setup.py build_sphinx

    - |
        echo "+++ Checking README for PyPy...."
        pip install -e .[dev]
        ./bin/check_readme.sh

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then pip install coveralls && coveralls; fi

